---
- name: setup AnsibleCI Agents
  hosts: agents
  vars_files:
    - /used_config/vault.yml
    - /used_config/aci.yml
    - /used_config/agents.yml
  roles:
    - de.iteratec.hh.ansible-ci-agent

- name: setup AnsibleCI pre live
  hosts: prelive
  vars_files:
    - /used_config/prelive.yml
  roles:
    - de.iteratec.hh.ansible-ci-prelive

- name: install Docker on ACI Server
  hosts: server
  become: yes

  tasks:

    - name: create configuration directory
      file:
        path: /etc/ansibleci
        state: directory

    - name: copy configuration files to server
      copy:
        src: /used_config/
        dest: /etc/ansibleci

    - name: start ACI Docker container
      docker:
        name: aci
        image: iteratechh/ansibleci
        volumes:
          - /etc/ansibleci:/ansible_config
        ports:
          - "24680:8080"
        env:
          ANSIBLE_VAULT_PASSWORD: "{{ ANSIBLE_VAULT_PASSWORD }}"
