WORKING_DIRECTORY: "{{ ansible_env.HOME }}/.ansible-data/de.iteratec.hh.ansible-ci-agent/vagrant"
DMIRROR_HOME: "{{ ansible_user_dir }}/.ansible-data/thomass.docker-mirror"
SQUID_HOME: "{{ ansible_user_dir }}/.ansible-data/thomass.squid-deb-proxy"
