---

# could be [server,development]
# see documentation of ansible-ci role
aci_install_type: development

# The Vagrant Box used for the tests
acia_vagrant_box: ubuntu/trusty64
# The amount of RAM the VM uses
acia_vagrant_memory: 3072
# The IP address of the ACIA vagrant virtual machine
acia_vagrant_ip: 172.28.128.3
# the SSH port to the ACIA vagrant virtual machine
acia_vagrant_port: 22

# port for the squid-deb-proxy container
acia_squid_port: 8000
# port for the docker cache proxy
acia_dmirror_port: 5000
