---

- name: update python-pip
  become: yes
  pip:
    name: pip
    executable: /usr/local/bin/pip
    state: latest

- name: install python docker library
  become: yes
  pip:
    name: docker-py
    executable: /usr/local/bin/pip
    state: latest
