---

- name: Add docker gpg key
  become: yes
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  register: addgpgkey
  until: addgpgkey | success
  retries: 5
  delay: 60

- name: create /etc/apt/sources.list.d/docker.list file
  become: yes
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: 0644
  register: sourcelist

- name: install docker
  become: yes
  apt:
    name: docker-engine
    state: present
    force: yes
    update_cache: "{{ sourcelist.changed }}"

- name: ensure docker service is running
  become: yes
  service:
    name: docker
    state: running
    enabled: yes

- name: install python-pip to install python libraries
  become: yes
  apt:
    name: "python-pip"
    state: present
    force: yes

- name: update python-pip
  become: yes
  pip:
    name: pip
    state: latest

- name: install python docker library
  become: yes
  pip:
    name: docker-py
    state: latest

- name: add user to docker group to allow use of docker without sudo
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: create docker alias [d,dbox] for quick use of docker functionality
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    state: present
  with_items:
    - alias d="docker"
    - dbox() { docker run -it --rm --name dbox $* ubuntu bash; }

- name: allow remote access to docker daemon if configured
  include: remoteconfig.yml
  when: docker_server_domain is defined
